const F = {
  awd:"Symmetrical All-Wheel Drive", turbo:"Turbocharged boxer engine", eye:"EyeSight driver assist",
  xmode:"X-Mode with hill descent", leather:"Leather upholstery", roof:"Sunroof",
  cam:"Reverse camera", cruise:"Adaptive cruise control", heat:"Heated front seats",
  key:"Keyless entry and push start", cp:"Apple CarPlay", aa:"Android Auto",
  rails:"Roof rails", led:"LED headlamps", paddle:"Paddle shifters", bi:"Bi-xenon projectors",
  diff:"Limited-slip differential", si:"SI-Drive modes", susp:"Sport-tuned suspension",
  tow:"Tow bar fitted", boot:"Powered tailgate", nav:"Factory navigation"
};

const imgs = (env, body) => [
  {kind:"side", env}, {kind:"front", env}, {kind:"rear", env},
  {kind:"interior", env}, {kind:"wheel", env}, {kind:"detail", env}
];

const SEED_CARS = [
  { model:"Forester", variant:"XT", year:2018, price:4250000, mileage:78000,
    engine:"2.0L FA20 turbocharged boxer", transmission:"Lineartronic CVT", fuel:"Petrol",
    drive:"Symmetrical AWD", body:"SUV", extColor:"Crystal White Pearl", intColor:"Black leather",
    regYear:2021, featured:true, images:imgs("ngong"),
    features:[F.awd,F.turbo,F.eye,F.xmode,F.leather,F.roof,F.cam,F.key,F.cp,F.paddle],
    description:"The XT is the Forester that answers back. A 2.0-litre turbo boxer under a body that still swallows a family, a weekend and a rough diversion outside Naivasha. This one came in on a single-owner import, full service record, and has spent its Kenyan life on tarmac." },
  { model:"Outback", variant:"2.5i Limited", year:2017, price:4950000, mileage:92000,
    engine:"2.5L FB25 boxer", transmission:"Lineartronic CVT", fuel:"Petrol",
    drive:"Symmetrical AWD", body:"Wagon", extColor:"Dark Blue Pearl", intColor:"Ivory leather",
    regYear:2020, images:imgs("rift"),
    features:[F.awd,F.eye,F.xmode,F.leather,F.cruise,F.cam,F.rails,F.boot,F.nav],
    description:"Ground clearance of an SUV, manners of an estate. The Outback is the quiet answer to Kenyan roads that change surface without warning, and it remains the most comfortable long-distance car we stock." },
  { model:"XV", variant:"2.0i-S", year:2016, price:2850000, mileage:96000,
    engine:"2.0L FB20 boxer", transmission:"Lineartronic CVT", fuel:"Petrol",
    drive:"Symmetrical AWD", body:"Hatchback", extColor:"Desert Khaki", intColor:"Black cloth",
    regYear:2019, images:imgs("highway"),
    features:[F.awd,F.xmode,F.cam,F.key,F.led,F.rails],
    description:"The easiest Subaru to live with in Nairobi traffic, and the cheapest way into symmetrical all-wheel drive. Compact outside, genuinely useful inside, and unbothered by a wet Ngong Road." },
  { model:"Forester", variant:"2.0i-L", year:2015, price:3650000, mileage:112000,
    engine:"2.0L FB20 boxer", transmission:"Lineartronic CVT", fuel:"Petrol",
    drive:"Symmetrical AWD", body:"SUV", extColor:"Sepia Bronze", intColor:"Black cloth",
    regYear:2018, images:imgs("ngong"),
    features:[F.awd,F.xmode,F.cam,F.key,F.rails,F.cruise],
    description:"The default sensible Subaru. Tall glass, a huge boot, and the visibility that makes a school run and a murram track equally uneventful." },
  { model:"WRX", variant:"STI", year:2016, price:5800000, mileage:64000,
    engine:"2.5L EJ257 turbocharged boxer", transmission:"6-speed manual", fuel:"Petrol",
    drive:"Symmetrical AWD", body:"Sedan", extColor:"WR Blue Pearl", intColor:"Black and blue Recaro",
    regYear:2019, featured:true, images:imgs("nairobi"),
    features:[F.awd,F.turbo,F.diff,F.si,F.susp,F.bi,F.paddle,F.cam],
    description:"Six gears, a centre differential you can dial in yourself, and the only Subaru on this page that asks something of you. Kept standard, serviced on schedule, and never tracked." },
  { model:"Impreza", variant:"1.6i Sport", year:2017, price:2650000, mileage:74000,
    engine:"1.6L FB16 boxer", transmission:"Lineartronic CVT", fuel:"Petrol",
    drive:"Symmetrical AWD", body:"Hatchback", extColor:"Ice Silver Metallic", intColor:"Black cloth",
    regYear:2020, images:imgs("highway"),
    features:[F.awd,F.cam,F.key,F.cp,F.aa,F.led],
    description:"Light on fuel, light on its feet, and still all-wheel drive. A first Subaru that does not feel like a compromise." },
  { model:"Legacy", variant:"B4", year:2015, price:2950000, mileage:118000,
    engine:"2.0L FB20 boxer", transmission:"Lineartronic CVT", fuel:"Petrol",
    drive:"Symmetrical AWD", body:"Sedan", extColor:"Carbide Grey", intColor:"Black leather",
    regYear:2018, images:imgs("nairobi"),
    features:[F.awd,F.leather,F.cruise,F.cam,F.key,F.roof],
    description:"The saloon for someone who wants the drivetrain without the ride height. Quiet at 120 on the Nairobi–Nakuru, and it hides its all-wheel drive until the weather turns." },
  { model:"Levorg", variant:"1.6 GT-S", year:2016, price:3450000, mileage:88000,
    engine:"1.6L FB16 direct-injection turbo", transmission:"Lineartronic CVT", fuel:"Petrol",
    drive:"Symmetrical AWD", body:"Wagon", extColor:"Crystal Black Silica", intColor:"Black leather",
    regYear:2019, images:imgs("coast"),
    features:[F.awd,F.turbo,F.eye,F.leather,F.paddle,F.si,F.cam,F.led],
    description:"A turbocharged estate that never officially came to most markets. Small engine, real boost, and a boot that takes a fortnight of luggage to Diani." },
  { model:"BRZ", variant:"S", year:2017, price:4100000, mileage:52000,
    engine:"2.0L FA20 boxer", transmission:"6-speed manual", fuel:"Petrol",
    drive:"Rear-wheel drive", body:"Coupe", extColor:"Pure Red", intColor:"Black alcantara",
    regYear:2020, images:imgs("mtkenya"),
    features:[F.diff,F.susp,F.paddle,F.cam,F.key,F.bi],
    description:"The exception on this floor: the only Subaru we sell that sends everything to the rear wheels. Low, light, and the most fun per shilling in the collection." },
  { model:"Outback", variant:"2.5i Touring", year:2019, price:6250000, mileage:48000,
    engine:"2.5L FB25 boxer", transmission:"Lineartronic CVT", fuel:"Petrol",
    drive:"Symmetrical AWD", body:"Wagon", extColor:"Magnetite Grey", intColor:"Tan leather",
    regYear:2022, images:imgs("mtkenya"),
    features:[F.awd,F.eye,F.xmode,F.leather,F.cruise,F.heat,F.boot,F.nav,F.cp,F.aa],
    description:"The newest car in the collection and the one we would take to Loiyangalani without a second thought. EyeSight, heated leather, and 48,000 honest kilometres." },

  { model:"Forester", variant:"2.0XT", year:2014, price:2980000, mileage:134000, status:"SOLD",
    engine:"2.0L FA20 turbocharged boxer", transmission:"Lineartronic CVT", fuel:"Petrol",
    drive:"Symmetrical AWD", body:"SUV", extColor:"Satin White Pearl", intColor:"Black cloth",
    regYear:2017, images:imgs("ngong"), features:[F.awd,F.turbo,F.xmode,F.cam],
    description:"Sold to a family in Karen after eleven days on the floor." },
  { model:"XV", variant:"2.0i", year:2015, price:2450000, mileage:121000, status:"SOLD",
    engine:"2.0L FB20 boxer", transmission:"Lineartronic CVT", fuel:"Petrol",
    drive:"Symmetrical AWD", body:"Hatchback", extColor:"Plasma Green", intColor:"Black cloth",
    regYear:2018, images:imgs("highway"), features:[F.awd,F.cam,F.key],
    description:"Went to Eldoret with 121,000 km and a fresh timing service." },
  { model:"WRX", variant:"2.0 CVT", year:2015, price:5200000, mileage:71000, status:"SOLD",
    engine:"2.0L FA20 turbocharged boxer", transmission:"Sport Lineartronic", fuel:"Petrol",
    drive:"Symmetrical AWD", body:"Sedan", extColor:"WR Blue Pearl", intColor:"Black leather",
    regYear:2018, images:imgs("nairobi"), features:[F.awd,F.turbo,F.si,F.susp],
    description:"Bought by its second Kenyan owner within a week of listing." },
  { model:"Legacy", variant:"2.5i", year:2016, price:3150000, mileage:99000, status:"SOLD",
    engine:"2.5L FB25 boxer", transmission:"Lineartronic CVT", fuel:"Petrol",
    drive:"Symmetrical AWD", body:"Sedan", extColor:"Ice Silver Metallic", intColor:"Grey cloth",
    regYear:2019, images:imgs("rift"), features:[F.awd,F.cruise,F.cam,F.key],
    description:"A company car that became a family car." },
  { model:"Outback", variant:"2.5i", year:2016, price:4350000, mileage:105000, status:"SOLD",
    engine:"2.5L FB25 boxer", transmission:"Lineartronic CVT", fuel:"Petrol",
    drive:"Symmetrical AWD", body:"Wagon", extColor:"Wilderness Green", intColor:"Black leather",
    regYear:2019, images:imgs("coast"), features:[F.awd,F.leather,F.rails,F.tow],
    description:"Left the yard towing a boat trailer to Naivasha." }
];

const SEED_STORIES = [
  { title:"Why we only sell Subaru", category:"Ownership", author:"Wanjiru Kamau", cover:{kind:"landscape",env:"ngong"},
    excerpt:"A single make is a constraint. Constraints make a dealership better at the thing it does.",
    body:["Most dealerships in Nairobi sell whatever lands at Mombasa. We decided early that we would rather know one make completely than know twenty makes approximately.",
"That decision changes everything downstream. We know which chassis codes had head gasket revisions and which did not. We know the difference in how a CVT behaves at 80,000 kilometres versus 140,000. We know which importers look after a car on the water and which ones do not.",
"## What a constraint buys you","When a Forester arrives, we are not learning it. We are checking it against every other Forester we have handled. That is the entire argument for specialising, and it is the reason a car that fails our inspection never reaches this website.",
"It also means we can be honest about the cars we do not stock. If you want a diesel seven-seater, we are the wrong shop, and we will say so on the phone rather than after you have driven to Runda."]},
  { title:"Nairobi to Loiyangalani in an Outback", category:"Road Trips", author:"Brian Otieno", cover:{kind:"landscape",env:"rift"},
    excerpt:"Eight hundred kilometres, two fuel stops and one stretch of road that is not really a road.",
    body:["The tarmac ends somewhere past Loruk and does not properly return. What follows is four hours of corrugation, volcanic gravel and the occasional dry river crossing that will find any weakness in a suspension.",
"We took a 2017 Outback with 92,000 kilometres on it, standard tyres swapped for all-terrains, and nothing else changed.",
"## The case for ground clearance","Two hundred and thirteen millimetres does not sound like much until you watch a lower crossover pick its line for twenty minutes over ground the Outback simply drove across. X-Mode did the rest on the loose climbs above the lake.",
"We arrived with a cracked number plate surround and a full tank of confidence. The car needed nothing beyond a wash."]},
  { title:"Symmetrical AWD, explained without the brochure", category:"Technology", author:"Wanjiru Kamau", cover:{kind:"detail",env:"mtkenya"},
    excerpt:"Why the layout matters more on a wet Waiyaki Way than it does in an advertisement.",
    body:["Most all-wheel-drive cars start as front-wheel-drive cars and add a driveshaft to the rear as an afterthought. The result is asymmetric: the power takes a different path to each side.",
"Subaru mounts a flat boxer engine in line with the transmission and runs the driveshaft straight down the centre. Left and right halves of the drivetrain are near mirror images.",
"## What you actually feel","A lower centre of gravity, and a car that stays neutral when a wet lane changes camber under you. It is not a device for going faster. It is a device for being surprised less often.",
"On Kenyan roads, where a dry lane can become a sheet of water in November without warning, that is worth more than an extra fifty horsepower."]},
  { title:"Buying a used Subaru in Kenya: the checklist", category:"Guides", author:"Brian Otieno", cover:{kind:"wheel",env:"highway"},
    excerpt:"Twelve things to look at before money changes hands, in the order we look at them.",
    body:["Start underneath. Rust on a Kenyan coastal car behaves differently to rust on an upcountry car, and the rear subframe tells the truth faster than the body panels.",
"## Drivetrain","On a CVT car, drive it from cold and hold a steady 60. A shudder that fades as the fluid warms is a conversation, not necessarily a deal breaker — but it must be priced in.",
"On a turbo car, check the oil before the engine is started and check the service intervals against the odometer. Turbo boxers are not fragile. Turbo boxers with skipped oil changes are.",
"## Paper","Match the chassis number on the logbook to the plate on the firewall, confirm the import date, and confirm the duty was paid by the importer and not left for you."]},
  { title:"Three new arrivals this month", category:"New Arrivals", author:"Sheriff Motors", cover:{kind:"side",env:"nairobi"},
    excerpt:"A Levorg GT-S, a low-mileage Touring Outback and a manual BRZ join the collection.",
    body:["The Levorg is the interesting one. A 1.6 direct-injection turbo in an estate body, sold mainly in Japan, and quick enough to make the small engine badge look like a typing error.",
"The Touring Outback arrives with 48,000 kilometres and full EyeSight. It is the newest car we have had on the floor this year.",
"## And one exception","The BRZ breaks our own rule: it is the only Subaru we stock that does not drive all four wheels. We took it anyway. Some cars earn an exception."]},
  { title:"Keeping a boxer engine happy past 150,000 km", category:"Maintenance", author:"Wanjiru Kamau", cover:{kind:"interior",env:"coast"},
    excerpt:"Oil, timing, and the two gaskets everyone worries about.",
    body:["The flat-four has a reputation it partly deserves and partly inherited from a specific generation of head gaskets that has long since been revised.",
"## Oil is the whole argument","Every 5,000 kilometres on a turbo, every 7,500 on a naturally aspirated car, with a grade that suits Nairobi's altitude and heat. This single habit separates the engines that reach 250,000 kilometres from the ones that do not.",
"## Listen at cold start","A brief rattle that disappears within two seconds is usually the oil pressure catching up. A rattle that persists is a timing chain tensioner, and it is cheaper to address the week you hear it.",
"Beyond that, a boxer asks for very little. Coolant on schedule, spark plugs at the interval, and a driver who lets the turbo idle for thirty seconds after a hard run."]}
];

const PART_CATS = ["Filters","Brakes","Suspension","Engine","Electrical","Body & Trim","Fluids","Accessories"];

const SEED_PARTS = [
  {sku:"OF-EJ25-001", name:"Engine Oil Filter", category:"Filters", brand:"Subaru Genuine",
    compatible:["Forester","Outback","Legacy","Impreza","XV"], price:1200, cost:650, stock:34, unit:"pcs",
    description:"Genuine spin-on oil filter for EJ and FB series boxer engines. Change every 5,000–7,500 km."},
  {sku:"AF-FB20-014", name:"Air Filter Element", category:"Filters", brand:"Subaru Genuine",
    compatible:["Forester","XV","Impreza"], price:2400, cost:1300, stock:22, unit:"pcs",
    description:"OEM panel air filter for FB20 and FB25 engines."},
  {sku:"CF-UNI-009", name:"Cabin Pollen Filter", category:"Filters", brand:"Aftermarket premium",
    compatible:["Forester","Outback","XV","Impreza","Legacy"], price:1800, cost:900, stock:40, unit:"pcs",
    description:"Activated-carbon cabin filter, fits most Subaru models 2012 onward."},
  {sku:"BP-FRT-221", name:"Front Brake Pad Set", category:"Brakes", brand:"Subaru Genuine",
    compatible:["Forester","Outback","XV"], price:6800, cost:3900, stock:16, unit:"set",
    description:"Genuine front pad set. Fits Forester and Outback 2013–2019."},
  {sku:"BP-RR-118", name:"Rear Brake Pad Set", category:"Brakes", brand:"Subaru Genuine",
    compatible:["Forester","Outback","Legacy"], price:5400, cost:3000, stock:14, unit:"set",
    description:"Genuine rear pad set for Forester, Outback and Legacy."},
  {sku:"BD-FRT-330", name:"Front Brake Disc (pair)", category:"Brakes", brand:"Aftermarket premium",
    compatible:["Forester","WRX","Outback"], price:14500, cost:8600, stock:6, unit:"pair",
    description:"Vented front rotors, direct OEM fitment."},
  {sku:"SS-STR-045", name:"Front Strut Assembly", category:"Suspension", brand:"KYB",
    compatible:["Forester","Impreza","XV"], price:12800, cost:7800, stock:8, unit:"pcs",
    description:"Complete strut assembly — a common wear item on Kenyan roads."},
  {sku:"SS-LNK-012", name:"Sway Bar Link Kit", category:"Suspension", brand:"Aftermarket premium",
    compatible:["Forester","Outback","Legacy","WRX"], price:3200, cost:1700, stock:20, unit:"kit",
    description:"Front sway bar end links, sold as a pair."},
  {sku:"TB-EJ-077", name:"Timing Belt Kit", category:"Engine", brand:"Gates",
    compatible:["Legacy","Outback"], price:9600, cost:5900, stock:5, unit:"kit",
    description:"Timing belt, tensioner and idler kit for EJ-series engines."},
  {sku:"HG-EJ25-003", name:"Head Gasket Set", category:"Engine", brand:"Subaru Genuine",
    compatible:["Forester","Outback","Legacy","Impreza"], price:11400, cost:7200, stock:4, unit:"set",
    description:"Revised-specification head gasket set for EJ25 engines."},
  {sku:"BT-N50-002", name:"Car Battery — N50", category:"Electrical", brand:"Amaron",
    compatible:["Forester","Outback","XV","Impreza","Legacy","WRX"], price:13500, cost:9000, stock:12, unit:"pcs",
    description:"Maintenance-free 12V battery, fits most Subaru passenger models."},
  {sku:"LB-H11-014", name:"Headlamp Bulb H11", category:"Electrical", brand:"Philips",
    compatible:["Forester","XV","Impreza"], price:1100, cost:550, stock:50, unit:"pair",
    description:"Long-life halogen headlamp bulbs, sold as a pair."},
  {sku:"WM-RF-019", name:"Roof Rail Crossbars", category:"Body & Trim", brand:"Subaru Genuine",
    compatible:["Forester","Outback","Levorg"], price:8200, cost:4900, stock:9, unit:"set",
    description:"Genuine lockable crossbars for factory roof rails."},
  {sku:"WM-MG-006", name:"Mud Guard Set", category:"Body & Trim", brand:"Subaru Genuine",
    compatible:["Forester","XV","Outback"], price:4600, cost:2400, stock:18, unit:"set",
    description:"Front and rear mud guards, genuine fitment."},
  {sku:"OL-5W30-004", name:"Synthetic Engine Oil 5W-30 (5L)", category:"Fluids", brand:"Subaru Genuine",
    compatible:["Forester","Outback","Legacy","Impreza","XV","WRX"], price:6200, cost:3800, stock:26, unit:"5L",
    description:"Full synthetic oil to factory specification."},
  {sku:"CV-LLC-002", name:"Long-Life Coolant (5L)", category:"Fluids", brand:"Subaru Genuine",
    compatible:["Forester","Outback","Legacy","Impreza"], price:3400, cost:1900, stock:19, unit:"5L",
    description:"Pre-mixed long-life coolant, safe for all Subaru engines."},
  {sku:"FM-TXT-008", name:"All-Weather Floor Mats", category:"Accessories", brand:"Aftermarket premium",
    compatible:["Forester","Outback","XV","Impreza","Legacy","WRX"], price:5800, cost:2900, stock:15, unit:"set",
    description:"Moulded all-weather mats, front and rear."},
  {sku:"CC-DASH-001", name:"Dash Cam — Front and Rear", category:"Accessories", brand:"70mai",
    compatible:["Forester","Outback","XV","Impreza","Legacy","WRX","BRZ"], price:9800, cost:6200, stock:11, unit:"pcs",
    description:"1080p front and rear dash camera with parking mode."},
  {sku:"OF-EJ25-STK0", name:"Engine Oil Filter — clearance", category:"Filters", brand:"Subaru Genuine",
    compatible:["Impreza"], price:900, cost:600, stock:0, unit:"pcs",
    description:"Last of an older filter revision — out of stock, kept listed while we reorder."}
];

const DEFAULT_SETTINGS = {
  dealership:"Sheriff Motors",
  tagline:"Carefully selected Subaru vehicles in Kenya.",
  whatsapp:"254700000000",
  phone:"+254 700 000 000",
  email:"hello@sheriffmotors.co.ke",
  address:"Kiambu Road, Runda, Nairobi",
  hours:"Mon–Fri 08:30–18:00 · Sat 09:00–16:00 · Sun by appointment",
  mapUrl:"https://maps.google.com/?q=Kiambu+Road+Nairobi",
  heroTitle:"Built for the journey.",
  heroSub:"Discover carefully selected Subaru vehicles in Kenya.",
  vatRate:16,
  pin:"",
  invoiceNote:"Thank you for your business. Vehicles remain the property of the dealership until paid in full.",
  receiptNote:"Thank you. Keep this receipt for your records.",
  aboutLead:"We are a small Nairobi dealership that sells one make, because one make is enough when it is the right one."
};

module.exports = { F, SEED_CARS, SEED_STORIES, PART_CATS, SEED_PARTS, DEFAULT_SETTINGS };
